#How to create and write to a file
file = open('sample.php','w')
file.write("<?php echo 'This is an autogenerated PHP file'?>")
file.close()

#Read a file

file = open('sample.php','r')
contents = file.read()
file.close()

print(contents)
